### PR TITLE
Use TextDecoder as a stream

### PR DESCRIPTION
**Pull request by phated**
@sttk Can you review these changes and determine if they work as expected?

### CODE REVIEW

**Comment by sttk** [comment]
@phated Thank you for your follow up! I understood the behavior of `TextDecoder.decoder` with `stream: true` option. 
It buffers an incomplete character (including BOM) and returns an empty string until receiving shortage bytes.

Since this change caused an error in a test case 'handles small chunks', I'll dig this code deeper.

**Comment by phated** [comment]
@sttk Where do you see the test failure? It works for me on node 16

**Comment by sttk** [comment]
@phated The test failure causes on node v10 and v11.

**Comment by sttk** [comment]
@phated The cause of the test failure is difference behavior between node<=11 and >=12.
We need to discard `chunk` if `Buffer.from(chunk)` is equal to `[0xEF, 0xBB, 0xBF]`

```js
// test.js
const util = require('util');
const decoder = new util.TextDecoder('utf-8', { ignoreBOM: false });

const BOM = Buffer.from([0xEF, 0xBB, 0xBF], 'utf-8');
const input = Buffer.concat([BOM, Buffer.from('Hello', 'utf-8')]);

console.log(Buffer.from(decoder.decode(input.slice(0, 1), { stream: true })));
console.log(Buffer.from(decoder.decode(input.slice(1, 2), { stream: true })));
console.log(Buffer.from(decoder.decode(input.slice(2, 3), { stream: true })));
console.log(Buffer.from(decoder.decode(input.slice(3, 4), { stream: true })));
```

```bash
% node -v
v11.15.0
% node test.js
<Buffer >
<Buffer >
<Buffer ef bb bf>
<Buffer 48>
```

```bash
% node -v
v12.19.0
% node test.js    
<Buffer >
<Buffer >
<Buffer >
<Buffer 48>
```

**Pull request merged**
